<?php

namespace app\models;

use Yii;

/**
 * This is the model class for table "car_model".
 *
 * @property int $id
 * @property int $category
 * @property string $name
 * @property int $price
 * @property string $picture
 * @property string $engine_volume
 * @property string $engine_type
 * @property double $fuel_consumption
 * @property int $seats
 * @property string $body
 * @property int $doors
 * @property string $transmission
 * @property int $air_conditioning
 * @property int $count
 *
 * @property Car[] $cars
 * @property Category $category0
 */
class CarModel extends \yii\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'car_model';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['category', 'price', 'seats', 'doors', 'air_conditioning', 'count'], 'integer'],
            [['fuel_consumption'], 'number'],
            [['name', 'picture', 'engine_volume', 'engine_type', 'body', 'transmission'], 'string', 'max' => 255],
            [['category'], 'exist', 'skipOnError' => true, 'targetClass' => Category::className(), 'targetAttribute' => ['category' => 'id']],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'category' => 'Category',
            'name' => 'Name',
            'price' => 'Price',
            'picture' => 'Picture',
            'engine_volume' => 'Engine Volume',
            'engine_type' => 'Engine Type',
            'fuel_consumption' => 'Fuel Consumption',
            'seats' => 'Seats',
            'body' => 'Body',
            'doors' => 'Doors',
            'transmission' => 'Transmission',
            'air_conditioning' => 'Air Conditioning',
            'count' => 'Count',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getCars()
    {
        return $this->hasMany(Car::className(), ['model' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getCategory0()
    {
        return $this->hasOne(Category::className(), ['id' => 'category']);
    }

    public function saveImage($filename)
    {
        $this->picture = $filename;
        return $this->save(false);
    }

    public function getPicture()
    {
        return ($this->picture) ? '/uploads/CarModels/' . $this->picture : '../../no_vehicle.png';
    }

    public function deleteImage()
    {
        $imageUploadModel = new ImageUpload();
        $imageUploadModel->deleteCurrentImage($this->picture);
    }

    public function beforeDelete()
    {
        $this->deleteImage();
        return parent::beforeDelete(); // TODO: Change the autogenerated stub
    }

    public function getCategory()
    {
        return $this->hasOne(Category::className(), ['id' => 'category']);
    }

    public function saveCategory($category_id)
    {
        $category = Category::findOne($category_id);
        if($category!=null)
        {
            $this->link('category', $category);
            return true;
        }
    }
}
